apiVersion: v1
kind: Pod
metadata:
  name: homeapp-prod
  labels:
    app: label-pod-homeapp-prod
spec:
  containers:
    - name: container-pod-homeapp-prod
      image: tigo17/home-app
      ports:
        - containerPort: 8180